In [3]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [5]:
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4431872/4422102 [==============================] - 0s 0us/step


In [6]:
train_images.shape

(60000, 28, 28)

In [7]:
len(train_labels)

60000

In [8]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [9]:
test_images.shape

(10000, 28, 28)

In [10]:
len(test_labels)

10000

In [11]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [12]:
train_images = train_images / 255.0
test_images = test_images / 255.0

In [13]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [15]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.5022 - accuracy: 0.8241
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3785 - accuracy: 0.8631
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3371 - accuracy: 0.8769
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3149 - accuracy: 0.8849
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2995 - accuracy: 0.8888


In [16]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)


313/313 [==============================] - 1s 1ms/step - loss: 0.3608 - accuracy: 0.8686
Test accuracy: 0.8686000108718872


In [17]:
predictions = model.predict(test_images)

In [18]:
predictions[0]


array([8.8857332e-06, 4.4594857e-05, 5.4748034e-07, 1.0269561e-05,
       2.6737081e-05, 7.1540177e-03, 6.2552607e-07, 1.7598690e-01,
       3.4454730e-04, 8.1642288e-01], dtype=float32)

In [19]:
np.argmax(predictions[0])


9

In [20]:
test_labels[0]

9

In [21]:
img = test_images[0]

print(img.shape)


(28, 28)


In [22]:
img = (np.expand_dims(img,0))

print(img.shape)


(1, 28, 28)


In [23]:
predictions_single = model.predict(img)

print(predictions_single)


[[8.8857096e-06 4.4594868e-05 5.4748045e-07 1.0269553e-05 2.6737114e-05
  7.1540084e-03 6.2552374e-07 1.7598680e-01 3.4454756e-04 8.1642306e-01]]


In [24]:
np.argmax(predictions_single[0])

9